[package]
name = "ingester_test_ctx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow-flight = { workspace = true }
bytes = "1.4.0"
data_types = { version = "0.1.0", path = "../data_types" }
dml = { version = "0.1.0", path = "../dml" }
futures = "0.3.28"
generated_types = { version = "0.1.0", path = "../generated_types" }
hashbrown.workspace = true
influxdb_iox_client = { path = "../influxdb_iox_client" }
ingester = { path = "../ingester" }
ingester_query_grpc = { path = "../ingester_query_grpc" }
iox_catalog = { version = "0.1.0", path = "../iox_catalog" }
iox_query = { version = "0.1.0", path = "../iox_query" }
iox_time = { path = "../iox_time" }
metric = { version = "0.1.0", path = "../metric" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
object_store = { workspace = true }
observability_deps = { version = "0.1.0", path = "../observability_deps" }
parquet_file = { version = "0.1.0", path = "../parquet_file" }
prost = { version = "0.11.9", default-features = false, features = ["std"] }
tempfile = { version = "3.8.0" }
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
tokio = { version = "1.32", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = "0.7.8"
tonic = { workspace = true }
trace = { version = "0.1.0", path = "../trace" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
