[package]
name = "schema"
description = "IOx Schema definition"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
hashbrown = { workspace = true }
indexmap = { version = "2.0", features = ["std"] }
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
